#!/usr/bin/python

# Copyright (c) 2010, 2014 Peter Palfrader
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Given a list of hashes from stdin, make a tarball of their files.

import tarfile
import sys
import yaml
import optparse
import os

parser = optparse.OptionParser()
parser.set_usage("%prog --config=<conffile>")
parser.add_option("-c", "--config", dest="conffile", metavar="CONFFILE",
  help="Config file location.")

(options, args) = parser.parse_args()
if options.conffile is None:
  parser.print_help()
  sys.exit(1)

config = yaml.safe_load(open(options.conffile).read())

def make_path(digest):
  prefix1 = digest[0:2]
  prefix2 = digest[2:4]
  return os.path.join(config['snapshot']['farmpath'], prefix1, prefix2, digest)

hexdigits = '0123456789abcdef'
def is_hex(s):
  return all(c in hexdigits for c in s)

tar = tarfile.open(mode="w|", fileobj=sys.stdout)
for line in sys.stdin:
  h = line.strip()
  if len(h) != 40 or not is_hex(h):
    print >>sys.stderr, "Ignoring invalid token %s"%(h)
    continue
  tar.add(make_path(h), arcname=h)
tar.close()

# vim:set et:
# vim:set ts=4:
# vim:set shiftwidth=4:
