#!/bin/bash

set -u

verbose=''
remote='snapshot-master.debian.org'
identity=""
remotefarmpath='farm'
localfarmpath="$HOME/farm"

usage() {
	echo "Usage: $0 [-v] [-r <remotehost>] [-i <sshidentityfile]"
}

set -- `getopt vr:i:h "$@"`
while [ "$#" -gt 0 ]; do
	case "$1" in
		-v)	verbose='--verbose';;
		-r)	remote="$2"; shift;;
		-i)	identity="$2"; shift;;
		--)	shift; break;;
		-h)	usage; exit 0;;
		-*)	usage >&2; exit 1;;
		*)	break;;
	esac
	shift
done
if [ "$#" -gt 0 ]; then usage >&2; exit 1; fi

c=""
h="0 1 2 3 4 5 6 7 8 9 a b c d e f"
for i in $h; do
	for j in $h; do
		c="$c $i$j"
	done
done


if [ -n "$identity" ] ; then
	export RSYNC_RSH="ssh -i $identity"
fi

for i in $c; do
	! [ -n "$verbose" ] || echo "Doing $i"
	rsync -az $verbose "$remote":"$remotefarmpath"/$i/ "$localfarmpath"/$i/
done
