#!/usr/bin/python

# Copyright (c) 2010 Peter Palfrader
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Check if all files in our farm have the correct content (i.e. the content hashes to their name)

import os
import re
import sys
import threading
import Queue
sys.path.append(os.path.abspath(os.path.dirname(sys.argv[0]))+'/lib/python2.5/site-packages')
import hasher



farmpath = '/srv/snapshot.debian.org/farm'
numthreads = 16
verbose = 2

queuesize = numthreads*2
workqueue = Queue.Queue(queuesize)
errors = []

class HashingThread(threading.Thread):
    def run(self):
        while True:
            item = workqueue.get()
            try:
                if item is None: break
                (path, filename) = item
                if verbose >= 6: print "%s: starting"%(filename)
                actual_hash = hasher.hash_file(os.path.join(path, filename))
                if actual_hash != filename:
                    errors.append((filename, 'Hash mismatch (%s)'%(actual_hash)))
                    if verbose >= 2: print "%s: Hash mismatch (%s)"%(filename, actual_hash)
                else:
                    if verbose >= 4: print "%s: OK"%(filename)
                    elif verbose >= 3: sys.stdout.write("."); sys.stdout.flush()
            except Exception, e:
                errors.append((filename, 'Exception: %s'%(e)))
                if verbose >= 2: print "%s: Exception (%s)"%(filename, e)
            finally:
                workqueue.task_done()

for x in xrange ( numthreads ):
   HashingThread().start()

try:
    for byte1 in xrange(256):
        if verbose >= 1: print "queueing %02x:"%(byte1)
        for byte2 in xrange(256):
            if verbose >= 2: print "queueing %02x%02x:"%(byte1, byte2)
            p = os.path.join(farmpath, '%02x'%byte1, '%02x'%byte2)
            for filename in os.listdir(p):
                if re.match('[0-9a-f]{40}$', filename) is None:
                    errors.append((filename, 'Invalid name'))
                    if verbose >= 2: print "Invalid name %s"%(filename)
                    continue
                if verbose >= 6: print "queueing %s"%(filename)
                workqueue.put((p, filename))
finally:
    for x in xrange ( numthreads ):
       workqueue.put(None)

workqueue.join()
for e in errors:
    print "%s: %s"%(e[0], e[1])

# vim:set ts=4:
# vim:set et:
# vim:set shiftwidth=4:
