#!/bin/bash

set -e
set -u

if [ -e /srv/snapshot.debian.org/IGNORE-UPDATE-TRIGGERS ]; then
	echo "Found IGNORE-UPDATE-TRIGGERS.  exiting."
	exit 0
fi

if [ -z "${1:-""}" ]; then
	echo "Usage: $0 <archivepath>" >&2
	exit 1
fi


archive="$1"
archive="${archive##/srv/mirrors/}"
archive="${archive%%/}"

#if [ "$archive" = "debian" ]; then
#      echo "Not accepting triggers for debian right now."
#      exit 0
#fi

logger -p user.info -t "snapshot-update-trugger" "Import run for $archive"

env -i /srv/snapshot.debian.org/bin/import-run "$archive"
