#!/usr/bin/python

import os
import stat
import errno
import fuse
import psycopg2

fuse.fuse_python_api = (0, 2)

connectstring = "dbname='snapshot' user='snapshot' host='localhost' password='x'"

class MyStat(fuse.Stat):
   def __init__(self):
      self.st_ino = 0
      self.st_dev = 0
      self.st_uid = 0
      self.st_gid = 0
      self.st_atime = 0
      self.st_mtime = 0
      self.st_ctime = 0

      self.st_mode = 0
      self.st_size = 0
      self.st_nlink = 1

class DirStat(MyStat):
   def __init__(self, subdirs=None):
      MyStat.__init__(self)
      self.st_mode = stat.S_IFDIR | 0755
      if subdirs is None:
         self.st_nlink = 1 # unknown
      else:
         self.st_nlink = 2+subdirs
      self.st_size = 4096

class SnapshotDB():
   def __init__(self):
      self.db=psycopg2.connect(connectstring)

   def query(self, *args, **kw):
      c = self.db.cursor()
      c.execute(*args, **kw)
      return c.fetchall()

   def query_firsts(self, *args, **kw):
      all = self.query(*args, **kw)
      return map(lambda x: x[0], all)


def split_path(path):
   path_elements = path.split('/',2)[1:]
   if len(path_elements) == 1:
      subpath = '/'
   else:
      subpath = '/'+path_elements[1]
   return(path_elements[0], subpath)


class MirrorRun():
   def __init__(self, db, id):
      self.db = db
      self.id = id

   def getattr(self, path):
      if path=='/':
         return DirStat() # XXX
      return -errno.ENOENT

   def readdir(self, path, offset):
      if path=='/':
         return []
      return -errno.ENOENT

class FSStaticElement():
   def __init__(self):
      self.elements = {}

   def getattr(self, path):
      (first, subpath) = split_path(path)
      if first == '':
         return DirStat(len(self.elements))
      elif first in self.elements:
         return self.elements[ first ].getattr(subpath)
      return -errno.ENOENT

   def readdir(self, path, offset):
      (first, subpath) = split_path(path)
      if first == '':
         return self.elements.keys()
      elif first in self.elements:
         return self.elements[ first ].readdir(subpath, offset)
      return -errno.ENOENT

class Archive(FSStaticElement):
   def __init__(self, db, id):
      FSStaticElement.__init__(self)
      self.db = db
      self.id = id
      self.load_elements()

   def load_elements(self):
      list = self.db.query("""SELECT mirrorrun_id, to_char(run, 'YYYYMMDD"T"HH24MISS')
                              FROM mirrorrun
                              WHERE archive_id=%(id)s""", {'id': self.id})
      for e in list:
         id = e[0]
         timestamp = e[1]
         self.elements[timestamp] = MirrorRun(self.db, id)


class Root(FSStaticElement):
   def __init__(self, db):
      FSStaticElement.__init__(self)
      self.db = db
      self.load_elements()

   def load_elements(self):
      list = self.db.query('SELECT archive_id, name FROM archive')
      for e in list:
         id = e[0]
         name = e[1]
         self.elements[name] = Archive(self.db, id)


class SnapshotFS(fuse.Fuse):
   def __init__(self, root, *args, **kw):
      fuse.Fuse.__init__(self, *args, **kw)
      self.root = root

   def getattr(self, path):
      return self.root.getattr(path)

   def readdir(self, path, offset):
      dirents = [ '.', '..' ]
      dirents.extend( self.root.readdir(path, offset) )
      for r in dirents:
         yield fuse.Direntry(r)

   def readlink(self, path):
      return hello_str

def main():
   db = SnapshotDB()
   root = Root(db)

   server = SnapshotFS(root, dash_s_do='setsingle')
   server.parse(errex=1)
   server.main()

if __name__ == '__main__':
   main()

# vim:set et:
# vim:set ts=3:
# vim:set shiftwidth=3:
