#!/bin/sh

# requires the dbutils external non-packaged python library.

set -e
set -x

TARGET="$HOME/web-app"
PYTARGET="$TARGET/lib/python2.5/site-packages"
dbutils="DBUtils-1.0.tar.gz"

[ -e "$dbutils" ]
[ -e "$HOME/code/web/app" ]
[ -w "$HOME/code/web/app/Snapshot.egg-info" ]

tmpdir=`mktemp -d`
trap "rm -rf '$tmpdir'" 0 1 2 5 15
tar xzf "$dbutils" -C "$tmpdir"

mkdir -v -p "$PYTARGET"
(cd "$tmpdir"/DBUtils-1.0 && PYTHONPATH="$PYTARGET" python setup.py install --single-version-externally-managed --record /dev/null --prefix="$TARGET")

find "$HOME"/code/web/app/Snapshot.egg-info -mindepth 1 -print0 | xargs -0 rm -v
(cd "$HOME"/code/web/app  && PYTHONPATH="$PYTARGET" python setup.py install --single-version-externally-managed --record /dev/null --prefix="$TARGET")

if ! [ -e "$HOME/web" ]; then
	mkdir "$HOME/web"
	ln -s ../web-app/lib/python2.5/site-packages/snapshot/public "$HOME/web/public"
fi
if ! [ -e "$HOME/web-cache" ]; then
	mkdir -m 01777 "$HOME/web-cache"
fi

echo
echo "If you do not have a config yet, run 'PYTHONPATH="$PYTARGET" paster make-config snapshot ~/etc/web-app.ini.NEW'"
